version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - 127.0.0.1:9200:9200
    volumes:
      - ./elastic:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  hive_3:
    image: thehiveproject/thehive:3.5
    depends_on:
      - elasticsearch
    volumes:
      - ./thehive-3.conf:/etc/thehive/application.conf
    ports:
      - "127.0.0.1:8999:9000"
    command: --no-config

  hive_4:
    image: thehiveproject/thehive4:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:9000:9000'
    volumes:
      - ./thehive-4.conf:/etc/thehive/application.conf
      - ./thehive-4-db:/tmp
      - ./thehive-4-data:/opt/data
    command: '--no-config --no-config-secret'
